# Generated by Django 3.0 on 2023-03-20 13:32

from django.db import migrations


def copy_data(apps, schem_editor):
    original_profile = apps.get_model('oc_lettings_site', 'Profile')
    new_profile = apps.get_model('profiles', 'Profile')
    objs = list()
    for profile in original_profile.objects.all():
        user = profile.user
        favorite_city = profile.favorite_city
        active_profil = new_profile(user=user, favorite_city=favorite_city)
        objs.append(active_profil)
    new_profile.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
