# Generated by Django 3.0 on 2023-03-20 11:41

from django.db import migrations


def copy_data(apps, schema_editor):
    original_letting = apps.get_model('oc_lettings_site', 'Letting')
    new_letting = apps.get_model('lettings', 'Letting')
    objs = list()
    new_address = apps.get_model('lettings', 'Address')
    fields = ('number',
              'street',
              'city',
              'state',
              'zip_code',
              'country_iso_code')
    for letting in original_letting.objects.all():
        title = letting.title
        original_address = letting.address
        dict_fields = {k: getattr(original_address, k, None) for k in fields}
        address, created = new_address.objects.get_or_create(**dict_fields)
        active_letting = new_letting(title=title, address=address)
        objs.append(active_letting)
    new_letting.objects.bulk_create(objs)


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
