version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

executors:
  python:
    docker:
      - image: cimg/python:3.10.10

jobs:
  build_and_test:
    executor: python
    resource_class: small
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: test
          command: pytest

  build_and_push_container:
    executor: python
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login Docker
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run:
          name: Build Docker Image
          command: |
                   docker build -t ${COMPANY}/python-oc-lettings-fr:${CIRCLE_SHA1} .
                   docker build -t ${COMPANY}/python-oc-lettings-fr:lastest .
      - run:
          name: Push Docker Image
          command: |
                   docker push ${COMPANY}/python-oc-lettings-fr:${CIRCLE_SHA1}
                   docker push ${COMPANY}/python-oc-lettings-fr:lastest
      

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Login Heroku
          command: heroku container:login
      - run:
          name: Pull Docker Container
          command: docker pull ${COMPANY}/python-oc-lettings-fr:${CIRCLE_SHA1}
      - run:
          name: Deploy On Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} docker tag ${COMPANY}/python-oc-lettings-fr:${CIRCLE_SHA1} registry.heroku.com/${HEROKU_APP_NAME}/web
            HEROKU_API_KEY=${HEROKU_API_KEY} docker push registry.heroku.com/${HEROKU_APP_NAME}/web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a ${HEROKU_APP_NAME}


workflows:
  master:
    jobs:
      - build_and_test
      - build_and_push_container:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_and_push_container
