version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.10.10
    resource_class: small

jobs:
  build_and_test:
    executor: python
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: test
          command: pytest

  build_and_push_docker_image:
    executor: python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login Docker
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run:
          name: Build Docker Image
          command: docker build -t ${DOCKER_USER}/Python-OC-Lettings-FR:${CIRCLE_SHA1}
      - run:
          name: Push Docker Image
          command: docker push ${DOCKER_USER}/Python-OC-Lettings-FR:${CIRCLE_SHA1}


workflows:
  master:
    jobs:
      - build_and_test
      - build_and_push_docker_image
