version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.10
    steps:
      - checkout
      - run:
          command: pip install -r requirements.txt
      - run:
          name: linting
          command: flake8
      - run:
          name: test
          command: pytest

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build_and_test
